# Generated by Django 4.1.7 on 2023-02-22 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_channel_name_alter_image_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
